name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v6

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Run tests
        run: |
          make test
